//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestPatcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestPatcher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Logs.
        /// </summary>
        public static string DisplayLogs {
            get {
                return ResourceManager.GetString("DisplayLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Generic_Browse {
            get {
                return ResourceManager.GetString("Generic_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Generic_Delete {
            get {
                return ResourceManager.GetString("Generic_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Generic_Off {
            get {
                return ResourceManager.GetString("Generic_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Generic_On {
            get {
                return ResourceManager.GetString("Generic_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Generic_Select {
            get {
                return ResourceManager.GetString("Generic_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK is 32 bit.
        /// </summary>
        public static string LoadedAPKStatus_32bit {
            get {
                return ResourceManager.GetString("LoadedAPKStatus_32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK is 64 bit.
        /// </summary>
        public static string LoadedAPKStatus_64bit {
            get {
                return ResourceManager.GetString("LoadedAPKStatus_64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK is modded.
        /// </summary>
        public static string LoadedAPKStatus_Modded {
            get {
                return ResourceManager.GetString("LoadedAPKStatus_Modded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK is not modded.
        /// </summary>
        public static string LoadedAPKStatus_NotModded {
            get {
                return ResourceManager.GetString("LoadedAPKStatus_NotModded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Version: {0}.
        /// </summary>
        public static string LoadedAPKStatus_Version {
            get {
                return ResourceManager.GetString("LoadedAPKStatus_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QP Version: {0}.
        /// </summary>
        public static string LoadedQPVersion {
            get {
                return ResourceManager.GetString("LoadedQPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestPatcher loading . . ..
        /// </summary>
        public static string LoadingView_QPLoading {
            get {
                return ResourceManager.GetString("LoadingView_QPLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modding Log.
        /// </summary>
        public static string LoggingDock_Title {
            get {
                return ResourceManager.GetString("LoggingDock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestLoader.
        /// </summary>
        public static string ModLoader_QuestLoader {
            get {
                return ResourceManager.GetString("ModLoader_QuestLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scotland2.
        /// </summary>
        public static string ModLoader_Scotland2 {
            get {
                return ResourceManager.GetString("ModLoader_Scotland2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file type to manage:.
        /// </summary>
        public static string OtherItems_ChooseType {
            get {
                return ResourceManager.GetString("OtherItems_ChooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load files.
        /// </summary>
        public static string OtherItems_FailToLoad {
            get {
                return ResourceManager.GetString("OtherItems_FailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait . . . .
        /// </summary>
        public static string OtherItems_Loading {
            get {
                return ResourceManager.GetString("OtherItems_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file types available for this app.
        /// </summary>
        public static string OtherItems_NotAvailable {
            get {
                return ResourceManager.GetString("OtherItems_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string OtherItems_RemoveAll {
            get {
                return ResourceManager.GetString("OtherItems_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string OtherItems_RemoveSelected {
            get {
                return ResourceManager.GetString("OtherItems_RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you install mods, QuestPatcher must patch your app.
        ///This may take several minutes depending on your internet connection.
        ///Make sure that your internet does not go offline during patching..
        /// </summary>
        public static string Patching_BeforeStartMessage {
            get {
                return ResourceManager.GetString("Patching_BeforeStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while patching completes . . ..
        /// </summary>
        public static string Patching_InProgress {
            get {
                return ResourceManager.GetString("Patching_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching Options.
        /// </summary>
        public static string Patching_PatchingOptions {
            get {
                return ResourceManager.GetString("Patching_PatchingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the mod loader to patch with: .
        /// </summary>
        public static string Patching_SelectModLoader {
            get {
                return ResourceManager.GetString("Patching_SelectModLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Splash Screen:.
        /// </summary>
        public static string Patching_SplashScreen {
            get {
                return ResourceManager.GetString("Patching_SplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Selected.
        /// </summary>
        public static string Patching_SplashScreen_None {
            get {
                return ResourceManager.GetString("Patching_SplashScreen_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch my App!.
        /// </summary>
        public static string Patching_StartPatching {
            get {
                return ResourceManager.GetString("Patching_StartPatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Debugging.
        /// </summary>
        public static string PatchingOption_Debugging {
            get {
                return ResourceManager.GetString("PatchingOption_Debugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow External Files.
        /// </summary>
        public static string PatchingOption_ExternalFiles {
            get {
                return ResourceManager.GetString("PatchingOption_ExternalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Tracking Type.
        /// </summary>
        public static string PatchingOption_HandTracking {
            get {
                return ResourceManager.GetString("PatchingOption_HandTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PatchingOption_HandTracking_None {
            get {
                return ResourceManager.GetString("PatchingOption_HandTracking_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1.
        /// </summary>
        public static string PatchingOption_HandTracking_V1 {
            get {
                return ResourceManager.GetString("PatchingOption_HandTracking_V1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V1 High Frequency.
        /// </summary>
        public static string PatchingOption_HandTracking_V1HighFrequency {
            get {
                return ResourceManager.GetString("PatchingOption_HandTracking_V1HighFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2.
        /// </summary>
        public static string PatchingOption_HandTracking_V2 {
            get {
                return ResourceManager.GetString("PatchingOption_HandTracking_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Microphone.
        /// </summary>
        public static string PatchingOption_Microphone {
            get {
                return ResourceManager.GetString("PatchingOption_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable VR Requirement.
        /// </summary>
        public static string PatchingOption_NoVRRequirement {
            get {
                return ResourceManager.GetString("PatchingOption_NoVRRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable OpenXR.
        /// </summary>
        public static string PatchingOption_OpenXR {
            get {
                return ResourceManager.GetString("PatchingOption_OpenXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} . . ..
        /// </summary>
        public static string Progress_Downloading {
            get {
                return ResourceManager.GetString("Progress_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0} . . ..
        /// </summary>
        public static string Progress_Extracting {
            get {
                return ResourceManager.GetString("Progress_Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Re-)Patch my app!.
        /// </summary>
        public static string Repatch_StartRepatching {
            get {
                return ResourceManager.GetString("Repatch_StartRepatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repatch App.
        /// </summary>
        public static string Repatch_Title {
            get {
                return ResourceManager.GetString("Repatch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new App.
        /// </summary>
        public static string SelectApp_Confirm {
            get {
                return ResourceManager.GetString("SelectApp_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading installed applications . . ..
        /// </summary>
        public static string SelectApp_Loading {
            get {
                return ResourceManager.GetString("SelectApp_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing your app will reload QuestPatcher to pull the new APK, which may take a minute or so..
        /// </summary>
        public static string SelectApp_Message {
            get {
                return ResourceManager.GetString("SelectApp_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Selected App.
        /// </summary>
        public static string SelectApp_Title {
            get {
                return ResourceManager.GetString("SelectApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Android devices are connected to your computer. Please select the device to use by clicking a row in the grid shown below..
        /// </summary>
        public static string SelectDevice_Message {
            get {
                return ResourceManager.GetString("SelectDevice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Device.
        /// </summary>
        public static string SelectDevice_Title {
            get {
                return ResourceManager.GetString("SelectDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Selected Device.
        /// </summary>
        public static string SelectDevice_WindowTitle {
            get {
                return ResourceManager.GetString("SelectDevice_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Management.
        /// </summary>
        public static string SideBarHeader_ModManage {
            get {
                return ResourceManager.GetString("SideBarHeader_ModManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools &amp; Options.
        /// </summary>
        public static string SideBarHeader_Options {
            get {
                return ResourceManager.GetString("SideBarHeader_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmetics &amp; other items.
        /// </summary>
        public static string SideBarHeader_Other {
            get {
                return ResourceManager.GetString("SideBarHeader_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching.
        /// </summary>
        public static string SideBarHeader_Patching {
            get {
                return ResourceManager.GetString("SideBarHeader_Patching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change App.
        /// </summary>
        public static string Tools_Option_ChangeApp {
            get {
                return ResourceManager.GetString("Tools_Option_ChangeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to select a different application to mod.
        /// </summary>
        public static string Tools_Option_ChangeApp_Description {
            get {
                return ResourceManager.GetString("Tools_Option_ChangeApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theming.
        /// </summary>
        public static string Tools_Option_Theme {
            get {
                return ResourceManager.GetString("Tools_Option_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows UI Customization.
        /// </summary>
        public static string Tools_Option_Theme_Description {
            get {
                return ResourceManager.GetString("Tools_Option_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Themes Folder.
        /// </summary>
        public static string Tools_Option_Theme_OpenThemeFolder {
            get {
                return ResourceManager.GetString("Tools_Option_Theme_OpenThemeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme:.
        /// </summary>
        public static string Tools_Option_Theme_SelectTheme {
            get {
                return ResourceManager.GetString("Tools_Option_Theme_SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Tools_Section_Options {
            get {
                return ResourceManager.GetString("Tools_Section_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestPatcher Settings..
        /// </summary>
        public static string Tools_Section_Options_Description {
            get {
                return ResourceManager.GetString("Tools_Section_Options_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools_Section_Tools {
            get {
                return ResourceManager.GetString("Tools_Section_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful for troubleshooting issues and managing your install..
        /// </summary>
        public static string Tools_Section_Tools_Description {
            get {
                return ResourceManager.GetString("Tools_Section_Tools_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dump.
        /// </summary>
        public static string Tools_Tool_CreateDump {
            get {
                return ResourceManager.GetString("Tools_Tool_CreateDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a dump containing lots of information about QuestPatcher and mod state..
        /// </summary>
        public static string Tools_Tool_CreateDump_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_CreateDump_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Logs Folder.
        /// </summary>
        public static string Tools_Tool_LogFolder {
            get {
                return ResourceManager.GetString("Tools_Tool_LogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the folder where QP stores logs..
        /// </summary>
        public static string Tools_Tool_LogFolder_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_LogFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Fix.
        /// </summary>
        public static string Tools_Tool_QuickFix {
            get {
                return ResourceManager.GetString("Tools_Tool_QuickFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears cached QuestPatcher data - try this if something isn&apos;t working..
        /// </summary>
        public static string Tools_Tool_QuickFix_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_QuickFix_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repatch App.
        /// </summary>
        public static string Tools_Tool_RepatchApp {
            get {
                return ResourceManager.GetString("Tools_Tool_RepatchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to change the modloader you have installed by re-patching your app..
        /// </summary>
        public static string Tools_Tool_RepatchApp_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_RepatchApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart App.
        /// </summary>
        public static string Tools_Tool_RestartApp {
            get {
                return ResourceManager.GetString("Tools_Tool_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes then reopens the selected app..
        /// </summary>
        public static string Tools_Tool_RestartApp_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_RestartApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts an ADB log - you must keep your quest plugged in while you use this..
        /// </summary>
        public static string Tools_Tool_ToggleADB_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_ToggleADB_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall App.
        /// </summary>
        public static string Tools_Tool_UninstallApp {
            get {
                return ResourceManager.GetString("Tools_Tool_UninstallApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalls your selected app..
        /// </summary>
        public static string Tools_Tool_UninstallApp_Description {
            get {
                return ResourceManager.GetString("Tools_Tool_UninstallApp_Description", resourceCulture);
            }
        }
    }
}
